### ISSUE TITLE
Input-container vertical reactive issue (solved)

### ISSUE THREAD

**Issue by Jungyeong-Eom** [Jungyeong-Eom/web_development_CSU-TU#2]
There was input-container vertical reactive issue like this
![Screenshot (99)](https://user-images.githubusercontent.com/71826916/104084530-2e8f3100-528b-11eb-98a4-798f7409a60f.png)

So that figure out this problem, I used media query to input-container. Now, there is no more vertical reactive issue in web_chat.html and week1-day4-assignment.html. If there are another bugs in these files we gonna discuss about that later.

**Comment by ggiande** [comment]
The previous solution only guarantees a fix when the viewport's height is less than a specific height. A permanent fix is to change the media screen height to 100vh. Expect new ggiande-demo PR to include the new patch. We can close this issue once the PR merges.

**Comment by Jungyeong-Eom** [comment]
Wow! that's really briliant! :)

**Comment by Jungyeong-Eom** [comment]
https://user-images.githubusercontent.com/71826916/104116495-7205a000-535c-11eb-9be7-dbe70a9f0c0a.mp4

Yeah, there is absolutely an error when using my original css with your html file.
I thought that caused by media query size property first...
But, the error was caused by missed bracket in media query!
